# Analysis
Loads, cleans, and analyzes the healthcare appointment dataset.

Computed results are pickled to `analysis_results.pkl` at the end, so `02_visualization.ipynb` can pick them up without recomputing anything.

In [64]:
import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')
from utils.filters import filter_appointments

In [65]:
# ── Load Data ──────────────────────────────────────────────────────────────────
df = pd.read_csv('../data/appointments.csv', parse_dates=['appointment_date'])
df.rename(columns={'specialty': 'doctor_specialty'}, inplace=True)

print("=== Dataset Overview ===")
print(f"Total Records : {len(df)}")
print(f"Date Range    : {df['appointment_date'].min().date()} → {df['appointment_date'].max().date()}")
print(f"Divisions     : {df['division'].nunique()}")
print(f"Specialties   : {df['doctor_specialty'].nunique()}\n")

print("=== Column Data Types ===")
print(df.dtypes)

print("=== First 3 Rows ===")
df.head(3)

=== Dataset Overview ===
Total Records : 500
Date Range    : 2023-01-02 → 2024-12-26
Divisions     : 8
Specialties   : 6

=== Column Data Types ===
patient_age                      int64
patient_gender                     str
division                           str
doctor_specialty                   str
appointment_status                 str
consultation_fee_bdt             int64
wait_days                        int64
appointment_date        datetime64[us]
dtype: object
=== First 3 Rows ===

,patient_age,patient_gender,division,doctor_specialty,appointment_status,consultation_fee_bdt,wait_days,appointment_date
0,56,Female,Chattogram,Gynecologist,Completed,914,4,2023-11-19
1,19,Male,Barishal,Cardiologist,Completed,1546,6,2024-06-07
2,76,Female,Dhaka,Pediatrician,Completed,725,1,2023-02-27

In [66]:
# ── Basic Cleaning ─────────────────────────────────────────────────────────────
print("=== Missing Values ===")
print(df.isnull().sum())

=== Missing Values ===
patient_age             0
patient_gender          0
division                0
doctor_specialty        0
appointment_status      0
consultation_fee_bdt    0
wait_days               0
appointment_date        0
dtype: int64

In [67]:
# Age group segmentation
bins = [0, 17, 35, 55, 100]
labels = ['Child (0-17)', 'Young Adult (18-35)', 'Middle Age (36-55)', 'Senior (56+)']
df['age_group'] = pd.cut(df['patient_age'], bins=bins, labels=labels)

print("=== First 3 Rows after adding Age Groups column ===")
df.head(3)

=== First 3 Rows after adding Age Groups column ===

,patient_age,patient_gender,division,doctor_specialty,appointment_status,consultation_fee_bdt,wait_days,appointment_date,age_group
0,56,Female,Chattogram,Gynecologist,Completed,914,4,2023-11-19,Senior (56+)
1,19,Male,Barishal,Cardiologist,Completed,1546,6,2024-06-07,Young Adult (18-35)
2,76,Female,Dhaka,Pediatrician,Completed,725,1,2023-02-27,Senior (56+)

In [68]:
# Extract month name for trend analysis
df['month'] = df['appointment_date'].dt.month
df['year'] = df['appointment_date'].dt.year
df['month_name'] = df['appointment_date'].dt.strftime('%b')

print("=== First 3 Rows after adding Month Year columns ===")
df.head(3)

=== First 3 Rows after adding Month Year columns ===

,patient_age,patient_gender,division,doctor_specialty,appointment_status,consultation_fee_bdt,wait_days,appointment_date,age_group,month,year,month_name
0,56,Female,Chattogram,Gynecologist,Completed,914,4,2023-11-19,Senior (56+),11,2023,Nov
1,19,Male,Barishal,Cardiologist,Completed,1546,6,2024-06-07,Young Adult (18-35),6,2024,Jun
2,76,Female,Dhaka,Pediatrician,Completed,725,1,2023-02-27,Senior (56+),2,2023,Feb

### Correlation Analysis

In [69]:
corr_matrix = df[['patient_age', 'consultation_fee_bdt', 'wait_days', 'month', 'year']].corr()
display(corr_matrix)

,patient_age,consultation_fee_bdt,wait_days,month,year
patient_age,1.000000,-0.058387,-0.000747,0.042031,-0.046246
consultation_fee_bdt,-0.058387,1.000000,-0.047631,-0.000729,0.102119
wait_days,-0.000747,-0.047631,1.000000,-0.001218,0.050077
month,0.042031,-0.000729,-0.001218,1.000000,0.013331
year,-0.046246,0.102119,0.050077,0.013331,1.000000

### Dynamic Filter Configuration
Set the division / specialty to filter into below. Every analysis cell and the summary at the end read from `filtered_df`, so changing these two lines re-scopes the whole notebook including the visualization notebook.

In [70]:
# ── Dynamic Filter Configuration ────────────────────────────────────────────────
# Leave a value as None to include everything for that field.
FILTER_DIVISION = "Dhaka"        # e.g. "Dhaka", "Chattogram", or None for all divisions
FILTER_SPECIALTY = None     # e.g. "Cardiologist", or None for all specialties

filtered_df = filter_appointments(df, division=FILTER_DIVISION, specialty=FILTER_SPECIALTY)

filter_label = " — ".join(p for p in [FILTER_DIVISION, FILTER_SPECIALTY] if p) or "All Divisions, All Specialties"

print(f"=== Active Filter: {filter_label} ===")
print(f"Filtered records: {len(filtered_df)} / {len(df)}")

=== Active Filter: Dhaka ===
Filtered records: 158 / 500

### Analyses 1:
Appointment Status Breakdown by specialty of each division

In [71]:
status_percentage = (
    filtered_df.groupby(['division', 'doctor_specialty'])['appointment_status']
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
    .rename('percentage')
)

status_count = (
    filtered_df.groupby(['division', 'doctor_specialty'])['appointment_status']
    .value_counts()
    .rename('count')
)

status_stats = (
    pd.concat([status_count, status_percentage], axis=1)
    .reset_index(['division', 'doctor_specialty', 'appointment_status'])
)

# Flat, chart-ready version
# overall counts for whatever is currently in filtered_df.
status_counts_vis = filtered_df['appointment_status'].value_counts()

print(f"=== Appointment Status ({filter_label}) ===")
display(status_stats)

=== Appointment Status (Dhaka) ===

   division   doctor_specialty appointment_status  count  percentage
0     Dhaka       Cardiologist          Completed     19        67.9
1     Dhaka       Cardiologist          Cancelled      5        17.9
2     Dhaka       Cardiologist            No-show      4        14.3
3     Dhaka      Dermatologist          Completed     19        59.4
4     Dhaka      Dermatologist          Cancelled      7        21.9
5     Dhaka      Dermatologist            No-show      6        18.8
6     Dhaka  General Physician          Completed     17        73.9
7     Dhaka  General Physician          Cancelled      4        17.4
8     Dhaka  General Physician            No-show      2         8.7
9     Dhaka       Gynecologist          Completed     16        64.0
10    Dhaka       Gynecologist          Cancelled      9        36.0
11    Dhaka         Orthopedic          Completed     12        54.5
12    Dhaka         Orthopedic          Cancelled      6        27.3
13    Dhaka         Orthopedic            No-show      4        18.2
14    Dhaka       Pediatrician          Completed     18        64.3
15    Dhaka       Pediatrician            No-show      7        25.0
16    Dhaka       Pediatrician          Cancelled      3        10.7

### Analysis 2: 
No-show Rate only by Division

In [72]:
noshow_by_division = (
    df.assign(is_noshow=(df['appointment_status'] == 'No-show'))
      .groupby('division')['is_noshow']
      .mean()
      .mul(100)
      .round(1)
      .reset_index(name='noshow_rate_pct')
      .sort_values('noshow_rate_pct', ascending=False)
)
noshow_by_division.columns = ['division', 'noshow_rate_pct']
print("=== No-show Rate by Division ===")
display(noshow_by_division)

=== No-show Rate by Division ===

     division  noshow_rate_pct
2       Dhaka             14.6
1  Chattogram             13.4
5    Rajshahi             11.7
7      Sylhet              9.3
4  Mymensingh              8.0
3      Khulna              6.7
0    Barishal              4.5
6     Rangpur              0.0

### Analysis 3: 
Analyses of Wait Days by Specialty of each division

In [73]:
wait_days_stats = (
    filtered_df.groupby(['division', 'doctor_specialty'])['wait_days']
    .agg(
        avg_wait_days='mean',
        median_wait_days='median',
        count='count',
        min_wait_days='min',
        max_wait_days='max',
        standard_deviation='std'
    )
    .round({'avg_wait_days': 1, 'median_wait_days': 1, 'standard_deviation': 1})
    .sort_values(by='avg_wait_days', ascending=False)
    .reset_index()
)

wait_days_stats['max_zscore'] = (
    (wait_days_stats['max_wait_days'] - wait_days_stats['avg_wait_days'])
    / wait_days_stats['standard_deviation']
).round(2)

# Flat, chart-ready version — average wait purely by specialty, OR division,
# for whatever is currently in filtered_df.
column_label = 'division' if (FILTER_SPECIALTY and not FILTER_DIVISION) else 'doctor_specialty'
heading_label = 'Division' if column_label == 'division' else 'Specialty'

avg_wait_days_vis = (
    filtered_df.groupby(column_label)['wait_days']
    .mean()
    .round(1)
    .reset_index(name='avg_wait_days')
    .sort_values(by='avg_wait_days', ascending=False)
)

specialty_demand_vis = (
    filtered_df[column_label]
    .value_counts()
    .reset_index(name='count')
)

wait_days_stats.dropna(subset=['standard_deviation'], inplace=True)
print(f"=== Wait Days by {heading_label} ({filter_label}) ===")
display(wait_days_stats)

=== Wait Days by Specialty (Dhaka) ===

,division,doctor_specialty,avg_wait_days,median_wait_days,count,min_wait_days,max_wait_days,standard_deviation,max_zscore
0,Dhaka,Orthopedic,12.3,12.0,22,3,20,4.8,1.60
1,Dhaka,General Physician,11.0,12.0,23,1,20,5.7,1.58
2,Dhaka,Gynecologist,11.0,12.0,25,1,19,6.1,1.31
3,Dhaka,Dermatologist,10.7,9.5,32,1,20,6.6,1.41
4,Dhaka,Pediatrician,10.1,10.5,28,1,20,5.7,1.74
5,Dhaka,Cardiologist,8.6,8.0,28,1,19,5.7,1.82

### Analysis 4: 
Age Group Distribution

In [74]:
age_order = [
    'Child (0-17)',
    'Young Adult (18-35)',
    'Middle Age (36-55)',
    'Senior (56+)'
]

df['age_group'] = pd.Categorical(
    df['age_group'],
    categories=age_order,
    ordered=True
)

age_group_count = (
    filtered_df.groupby(['division', 'doctor_specialty'])['age_group']
    .value_counts()
    .rename('count')
)

age_group_percentage = (
    filtered_df.groupby(['division', 'doctor_specialty'])['age_group']
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
    .rename('percentage')
)

age_group_stats = (
    pd.concat([age_group_count, age_group_percentage], axis=1)
    .reset_index(['age_group', 'division', 'doctor_specialty'])
)

# Flat, chart-ready version — age distribution of division/specialty.
age_dist_vis = (
    filtered_df['age_group']
    .value_counts()
    .reindex(age_order)
    .reset_index(name='count')
)

print("=== Patient Age Group Distribution ===")
display(age_group_stats)

=== Patient Age Group Distribution ===

   division   doctor_specialty            age_group  count  percentage
0     Dhaka       Cardiologist         Senior (56+)     11        39.3
1     Dhaka       Cardiologist         Child (0-17)      7        25.0
2     Dhaka       Cardiologist  Young Adult (18-35)      5        17.9
3     Dhaka       Cardiologist   Middle Age (36-55)      5        17.9
4     Dhaka      Dermatologist         Senior (56+)     15        46.9
5     Dhaka      Dermatologist   Middle Age (36-55)      7        21.9
6     Dhaka      Dermatologist  Young Adult (18-35)      5        15.6
7     Dhaka      Dermatologist         Child (0-17)      5        15.6
8     Dhaka  General Physician         Senior (56+)      7        30.4
9     Dhaka  General Physician   Middle Age (36-55)      7        30.4
10    Dhaka  General Physician  Young Adult (18-35)      5        21.7
11    Dhaka  General Physician         Child (0-17)      4        17.4
12    Dhaka       Gynecologist   Middle Age (36-55)      9        36.0
13    Dhaka       Gynecologist  Young Adult (18-35)      6        24.0
14    Dhaka       Gynecologist         Child (0-17)      6        24.0
15    Dhaka       Gynecologist         Senior (56+)      4        16.0
16    Dhaka         Orthopedic         Child (0-17)      9        40.9
17    Dhaka         Orthopedic         Senior (56+)      6        27.3
18    Dhaka         Orthopedic   Middle Age (36-55)      5        22.7
19    Dhaka         Orthopedic  Young Adult (18-35)      2         9.1
20    Dhaka       Pediatrician         Senior (56+)     11        39.3
21    Dhaka       Pediatrician         Child (0-17)      7        25.0
22    Dhaka       Pediatrician  Young Adult (18-35)      6        21.4
23    Dhaka       Pediatrician   Middle Age (36-55)      4        14.3

### Analysis 5: 
Monthly Appointment Trend

In [75]:
# Count appointments
monthly_trend = (
    filtered_df.groupby(['year', 'month', 'month_name'])
    .size()
    .reset_index(name='count')
)

# Create all year-month combinations
years = sorted(monthly_trend['year'].unique())
months = range(1, 13)

full_index = pd.MultiIndex.from_product(
    [years, months],
    names=['year', 'month']
)

# Reindex and fill missing months with 0 count
monthly_trend = (
    monthly_trend
    .set_index(['year', 'month'])
    .reindex(full_index)
    .reset_index()
)

monthly_trend['count'] = monthly_trend['count'].fillna(0).astype(int)

# Converts NaN to proper month names
monthly_trend['month_name'] = pd.to_datetime(
    monthly_trend['month'],
    format='%m'
).dt.strftime('%b')     

print(f"=== Monthly Appointment Trend ({filter_label}) ===")
display(monthly_trend)

=== Monthly Appointment Trend (Dhaka) ===

    year  month month_name  count
0   2023      1        Jan     11
1   2023      2        Feb      4
2   2023      3        Mar      6
3   2023      4        Apr      3
4   2023      5        May      5
5   2023      6        Jun      9
6   2023      7        Jul      5
7   2023      8        Aug      5
8   2023      9        Sep      1
9   2023     10        Oct      6
10  2023     11        Nov      7
11  2023     12        Dec      6
12  2024      1        Jan      9
13  2024      2        Feb     10
14  2024      3        Mar      6
15  2024      4        Apr      6
16  2024      5        May      7
17  2024      6        Jun      6
18  2024      7        Jul      8
19  2024      8        Aug      7
20  2024      9        Sep      7
21  2024     10        Oct     11
22  2024     11        Nov      4
23  2024     12        Dec      9

### Analysis 7:
Analyses of fees of Specialty of each division (No Visualization only data output)

In [76]:
fees_stats = (
    filtered_df.groupby(['division', 'doctor_specialty'])['consultation_fee_bdt']
    .agg(
        avg_fee='mean',
        median_fee = 'median',
        min_fee='min',
        max_fee='max',
        standard_deviation='std'
    )
    .round({'avg_fee': 1, 'median_fee': 1, 'standard_deviation': 1})
    .reset_index()
    .sort_values(by='avg_fee', ascending=False)
)

fees_stats['max_zscore'] = (
    (fees_stats['max_fee'] - fees_stats['avg_fee'])
    / fees_stats['standard_deviation']
).round(2)

fees_stats.dropna(subset=['standard_deviation'], inplace=True)

overall_avg_fee = (
    filtered_df.groupby(column_label)['consultation_fee_bdt']
    .mean()
    .round(1)
    .reset_index(name='avg_fee')
)

print(f"=== Consultation Fees by {heading_label} ({filter_label}) ===")
display(fees_stats)

=== Consultation Fees by Specialty (Dhaka) ===

,division,doctor_specialty,avg_fee,median_fee,min_fee,max_fee,standard_deviation,max_zscore
0,Dhaka,Cardiologist,1541.0,1531.5,1407,1693,81.3,1.87
4,Dhaka,Orthopedic,1267.4,1269.5,1122,1381,81.3,1.40
1,Dhaka,Dermatologist,1021.5,1021.5,900,1194,69.0,2.50
3,Dhaka,Gynecologist,1010.1,980.0,901,1189,84.9,2.11
5,Dhaka,Pediatrician,825.7,812.5,720,994,92.8,1.81
2,Dhaka,General Physician,551.0,559.0,412,680,67.1,1.92

In [77]:
# ── Key Findings Summary ────────────────────
print(f"\n=== Key Findings — {filter_label} ===")

if len(filtered_df) == 0:
    print("No records match this filter — try loosening FILTER_DIVISION / FILTER_SPECIALTY.")
else:
    completion_rate = round((filtered_df['appointment_status'] == 'Completed').mean() * 100, 1)
    print(f"• Records in view                 : {len(filtered_df)} ({round(len(filtered_df) / len(df) * 100, 1)}% of all data)")
    print(f"• Completion rate                 : {completion_rate}%")

    if not noshow_by_division.empty:
        top_noshow = noshow_by_division.iloc[0]
        print(f"• Division with highest no-show   : {top_noshow['division']} ({top_noshow['noshow_rate_pct']}%)")

    if not specialty_demand_vis.empty:
        index_label = column_label  
        top_specialty = specialty_demand_vis.iloc[0]
        print(f"• Most visited                    : {top_specialty[index_label]} ({top_specialty['count']} appointments)")

    if not avg_wait_days_vis.empty:
        longest_wait = avg_wait_days_vis.iloc[0]
        print(f"• Longest average wait            : {longest_wait[index_label]} ({longest_wait['avg_wait_days']} days)")

    if not age_dist_vis.empty and age_dist_vis['count'].sum() > 0:
        top_age_group = age_dist_vis.loc[age_dist_vis['count'].idxmax()]
        print(f"• Largest patient group           : {top_age_group['age_group']} ({top_age_group['count']} patients)")
        
    if not overall_avg_fee.empty:
        highest_avg_fee = overall_avg_fee.iloc[0]
        print(f"• Highest average consultation fee: {highest_avg_fee[index_label]} ({highest_avg_fee['avg_fee']} BDT)")

=== Key Findings — Dhaka ===
• Records in view                 : 158 (31.6% of all data)
• Completion rate                 : 63.9%
• Division with highest no-show   : Dhaka (14.6%)
• Most visited                    : Dermatologist (32 appointments)
• Longest average wait            : Orthopedic (12.3 days)
• Largest patient group           : Senior (56+) (54 patients)
• Highest average consultation fee: Cardiologist (1541.0 BDT)

In [78]:
# ── Save Results for visualization.ipynb ───────────────────────────────────────
results = {
    'df': df,
    'filtered_df': filtered_df,
    'filter_division': FILTER_DIVISION,
    'filter_specialty': FILTER_SPECIALTY,
    'filter_label': filter_label,
    'column_label': column_label,
    'status_stats': status_stats,
    'status_counts': status_counts_vis,
    'noshow_by_division': noshow_by_division,
    'specialty_wait': avg_wait_days_vis,
    'specialty_demand': specialty_demand_vis,
    'header_label': heading_label,
    'age_group_stats': age_group_stats,
    'age_dist': age_dist_vis,
    'monthly_trend': monthly_trend,
}

with open('analysis_results.pkl', 'wb') as f:
    pickle.dump(results, f)

print("Analysis results saved to analysis_results.pkl")

Analysis results saved to analysis_results.pkl